version: '3.7'

services:

  # Nginx server
  reverse-proxy:
    image: nginx
    container_name: reverse_proxy
    depends_on:
      - backend-service
      - frontend-service
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  # Backend-service
  backend-service:
    container_name: enodo-api
    build: ./enodo-api
    command: python manage.py runserver 0.0.0.0:9000
    volumes:
      - ./enodo-api:/usr/src/app/
    ports:
      - "9000:9000"

  # Frontend-service
  frontend-service:
    # container_name: enodo-gui
    build: ./enodo-app
    volumes:
      - './enodo-app:/app'
      - './enodo-app/node_modules:/app/node_modules'
    ports:
      - '9001-9005:8080'
