# Generated by Django 2.2 on 2020-10-01 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyinfo',
            options={'managed': True},
        ),
    ]
