# Generated by Django 2.2 on 2020-10-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyapp', '0002_auto_20201001_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinfo',
            name='is_selected',
            field=models.BooleanField(db_column='IS_SELECTED', default=False),
        ),
    ]
